### ISSUE TITLE
Including clj-uuid takes an additional 30s startup time on my OSX Yosemite MBP

### ISSUE THREAD

**Issue by CmdrDats** [danlentz/clj-uuid#26]
I've pinpointed this behaviour directly to the clj-uuid.node/all-local-addresses function.. For some reason this takes an absolutely obscene amount of time.

Ironically, I don't even use the v1 uuid's which this seems to be required for - so if this can't actually be sped up, can we at least only pay the setup cost if we actually need it?

**Comment by danlentz** [comment]
yikes.  yes, i can definitely do something about this, but, just of curiosity can you identify why on earth it might possibly be taking so long to query the vm for addresses?

**Comment by CmdrDats** [comment]
I copied the function into my project and ran it with some crude timing, and the bulk of the time is in the (.getCanonicalHostName localhost). It does it on my OSX Yosemite directly without a vm - I notice that I can't actually replicate on my vm, that must be a slowdown in a different place. I'll update the issue title.

**Comment by danlentz** [comment]
Ok, well that's odd.  I'm running a MacBookPro with Yosemite as well.  Can you help me to replicate your issue?

**Comment by danlentz** [comment]
@CmdrDats I've just been going through the javadocs for .getCanonicalHostname et al -- is there any chance this delay may have something to do with your DNS configuration?

**Comment by CmdrDats** [comment]
@danlentz It's absolutely likely - I tried again at work and I can't seem to replicate the same behaviour there. I don't have anything special about my network configuration. Not sure how one would go about isolating it so that you at least know what kind of network configuration is going to cause trouble

**Comment by danlentz** [comment]
from the command prompt on the symptomatic macbook, what are the results of the following commands?

`hostname`
`host \`hostname\``
`ifconfig en0` (or substitute primary interface name if other than en0)

**Comment by CmdrDats** [comment]
```
~ ❯❯❯ hostname                                                                                                                                      ⏎
Icy2-2.local
host `hostname`
ifconfig en0
~ ❯❯❯ host `hostname`
;; connection timed out; no servers could be reached
~ ❯❯❯ ifconfig en0                                                                                                                                  ⏎
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 6c:40:08:90:1f:06
	inet6 fe80::6e40:8ff:fe90:1f06%en0 prefixlen 64 scopeid 0x4
	inet 192.168.0.3 netmask 0xffffff00 broadcast 192.168.0.255
	nd6 options=1<PERFORMNUD>
	media: autoselect
	status: active
~ ❯❯❯ cat /etc/resolv.conf
#
# Mac OS X Notice
#
# This file is not used by the host name and address resolution
# or the DNS query routing mechanisms used by most processes on
# this Mac OS X system.
#
# This file is automatically generated.
#
nameserver 192.168.0.1
~ ❯❯❯
```

The `host 'hostname'` command took a couple of seconds to complete - unlike at work, where it was instantaneous. Note, that I'm checking on the same laptop at different networks.

**Comment by danlentz** [comment]
ok, `host 'hostname'` timed out.  your machine cannot resolve it's own address.  This is almost certainly going to turn up as an issue in other situations as well.  I don't know why your mDNSresponder is not resolving Bonjour local names -- you may want to track this down.  As a workaround, though, try adding the following line to your /etc/hosts file:

```
192.168.0.3    Icy2-2.local
```

**Comment by danlentz** [comment]
@CmdrDats Just wanted to check and see if you've had any success with this -- there are other things that can be done if you can't get DNS resolved, but possibly not as preferred.

**Comment by CmdrDats** [comment]
@danlentz Sorry about that - got a bit distracted because I can only test after hours at home.

I tried adding that to my `/etc/hosts` (with the new IP) but doesn't make a difference to the `host 'hostname'` call. I'm not sure how I'd test my DNS server - but it is my adsl router which doesn't seem to have a problem resolving addresses.

At least it's consistently a problem here at home!

**Comment by danlentz** [comment]
@CmdrDats Yes, no worries.  I started at a new job last week so I've also been distracted.  I'd still like to help make this more convenient for you, though, and as luck would have it, I now have a yosemite laptop in a dual work/remote configuration that may (hopefully) be at least partially analogous to yours.

So, with regards to `host 'hostname'`on this box with a brand new install, working from my home network with no configuration, that command returns immediately with `Host lentz-mbpr-1.local not found: 3(NXDOMAIN)` and clj-uuid compiles without any delay.  You are able to resolve other DNS addresses? (i.e., `host google.com` resolves and returns immediately?)

With regards to changing the code, I'm open to ideas.  I wouldn't want to just wrap the node id calculation in a delay, because I think that fundamentally breaks the contract of v1 from "guaranteed fast" to "best effort, worst case 30 seconds if you are unlucky" and I'd much rather pay that penalty (if I have to) at compile time and have predictable run-time behavior.  

One idea i had was that if there is no other way to help you, perhaps I can wrap the node id calculation in a time-out, say 5 seconds, and if it has not been fulfilled by the end of that time, fall back to choosing a random node id (while warning vociferously).   

But that said, my first instinct is that resolving your own hostname just shouldn't take 30 seconds to time out.  Even when it does not resolve (as in my test config) it should return immediately.

Let me know your thoughts.
Best,
Dan

**Comment by danlentz** [comment]
@CmdrDats I'm definitely happy to work with you to improve this, but for now until you have some time how about if we close the issue?

**Comment by CmdrDats** [comment]
Hi @danlentz, sure - sorry I didn't get back to you, been a bit of an intense time recently!

I suspect it's some badly setup local dns on my router, so it's not critical - I was just wary of this happening unbeknownst to someone in production. But, production machines _should_ be able to resolve their own hostnames, one would hope!
